const translations = {
  km: {
    app_name: 'Littlemaker', app_tagline: 'ប្រព័ន្ធគ្រប់គ្រងអាជីវកម្ម',
    nav_dashboard: 'ផ្ទាំងគ្រប់គ្រង', nav_products: 'ផលិតផល',
    nav_sales: 'ការលក់', nav_purchases: 'ការទិញ', nav_settings: 'ការកំណត់',
    add: 'បន្ថែម', edit: 'កែប្រែ', delete: 'លុប', save: 'រក្សាទុក',
    cancel: 'បោះបង់', search: 'ស្វែងរក...', confirm_delete: 'តើអ្នកចង់លុបមែនទេ?',
    total_products: 'ផលិតផលសរុប', total_sales: 'តម្លៃលក់សរុប',
    total_purchases: 'តម្លៃទិញសរុប', profit: 'ចំណេញសុទ្ធ',
    recent_sales: 'ការលក់ថ្មីៗ', recent_purchases: 'ការទិញថ្មីៗ',
    product_name: 'ឈ្មោះផលិតផល', category: 'ប្រភេទ',
    buy_price: 'តម្លៃទិញ (រៀល)', sell_price: 'តម្លៃលក់ (រៀល)',
    stock: 'ស្តុក', unit: 'ឯកតា', manage_products: 'គ្រប់គ្រងផលិតផល',
    add_product: 'បន្ថែមផលិតផល', edit_product: 'កែប្រែផលិតផល',
    manage_sales: 'គ្រប់គ្រងការលក់', add_sale: 'កត់ត្រាការលក់',
    customer: 'អតិថិជន', quantity: 'បរិមាណ', total: 'សរុប',
    date: 'កាលបរិច្ឆេទ', product: 'ផលិតផល', unit_price: 'តម្លៃ/ឯកតា',
    note: 'កំណត់ចំណាំ', sale_history: 'ប្រវត្តិការលក់',
    manage_purchases: 'គ្រប់គ្រងការទិញ', add_purchase: 'កត់ត្រាការទិញ',
    supplier: 'អ្នកផ្គត់ផ្គង់', purchase_history: 'ប្រវត្តិការទិញ',
    saved: '✓ រក្សាទុកជោគជ័យ!', deleted: '✓ លុបជោគជ័យ!',
    insufficient_stock: '⚠ ស្តុកមិនគ្រប់គ្រាន់!', fill_required: '⚠ សូមបំពេញព័ត៌មានចាំបាច់!',
    low_stock: 'ស្តុកជិតអស់', in_stock: 'មានស្តុក', out_stock: 'អស់ស្តុក',
    unit_pcs: 'ដុំ', unit_kg: 'គីឡូ', unit_liter: 'លីត្រ', unit_box: 'ប្រអប់', unit_pack: 'កញ្ចប់', unit_can: 'កំប៉ុង', unit_bottle: 'ដប',
    cat_food: 'អាហារ', cat_drink: 'គ្រឿងផឹក', cat_material: 'វត្ថុធាតុ', cat_other: 'ផ្សេងៗ',
    all_categories: 'ប្រភេទទាំងអស់', no_data: 'មិនមានទិន្នន័យ', items: 'មុខ',
    filter_date: 'ចំណាត់ចំណុចកាលបរិច្ឆេទ', today: 'ថ្ងៃនេះ', this_week: 'សប្តាហ៍នេះ',
    this_month: 'ខែនេះ', all_time: 'ទាំងអស់', actions: 'សកម្មភាព',
    profit_margin: 'ម៉ាស៊ីននៃចំណេញ', top_products: 'ផលិតផលដែលលក់ច្រើន',
    dashboard_summary: 'សង្ខេបទូទៅ',
    // Settings
    settings_title: 'ការកំណត់ប្រព័ន្ធ',
    settings_appearance: '🎨 ភាពបង្ហាញ',
    settings_language: 'ភាសា',
    settings_theme: 'របៀបបង្ហាញ',
    settings_theme_light: '☀️ ភ្លឺ',
    settings_theme_dark: '🌙 យប់',
    settings_theme_auto: '🔄 ស្វ័យប្រវត្តិ',
    settings_business: '🏪 ព័ត៌មានហាង',
    settings_biz_name: 'ឈ្មោះហាង',
    settings_biz_phone: 'លេខទូរស័ព្ទ',
    settings_biz_address: 'អាសយដ្ឋាន',
    settings_receipt_footer: 'អត្ថបទក្រោមវិក្កយបត្រ',
    settings_data: '💾 ការគ្រប់គ្រងទិន្នន័យ',
    settings_export_json: 'នាំចេញ JSON (ទិន្នន័យទាំងអស់)',
    settings_import_json: 'នាំចូល JSON',
    settings_reset: '🗑 លុបទិន្នន័យទាំងអស់',
    settings_reset_confirm: 'ការចង់លុបទិន្នន័យទាំងអស់? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ!',
    settings_saved: '✓ ការកំណត់ត្រូវបានរក្សាទុក!',
    settings_reset_done: '✓ ទិន្នន័យត្រូវបានលុបរួចហើយ!',
    settings_import_success: '✓ ទិន្នន័យត្រូវបាននាំចូលជោគជ័យ!',
    settings_import_error: '⚠ ឯកសារមិនត្រឹមត្រូវ!',
    settings_about: 'ℹ️ អំពីប្រព័ន្ធ',
    settings_version: 'កំណែ',
    settings_save_btn: 'រក្សាទុកការកំណត់',
    // Login
    login_title: 'ចូលប្រើប្រាស់', login_subtitle: 'ប្រព័ន្ធគ្រប់គ្រងអាជីវកម្ម',
    username: 'ឈ្មោះអ្នកប្រើ', password: 'លេខសម្ងាត់',
    login_btn: 'ចូល', logout_btn: 'ចាកចេញ',
    login_error: '⚠ ឈ្មោះអ្នកប្រើ ឬ លេខសម្ងាត់មិនត្រឹមត្រូវ!',
    login_required: '⚠ សូមបំពេញព័ត៌មានចាំបាច់!',
    remember_me: 'ចងចាំខ្ញុំ',
    settings_users: '👥 គ្រប់គ្រងអ្នកប្រើ',
    user_add: 'បន្ថែមអ្នកប្រើ', user_edit: 'កែប្រែអ្នកប្រើ',
    user_name_label: 'ឈ្មោះអ្នកប្រើ', user_display: 'ឈ្មោះបង្ហាញ',
    user_role: 'តួនាទី', role_admin: 'អ្នកគ្រប់គ្រង', role_staff: 'បុគ្គលិក',
    user_new_pass: 'លេខសម្ងាត់ថ្មី (ទុកចោលបើមិនផ្លាស់ប្តូរ)',
    logged_in_as: 'ចូលក្នុងជា',
    session_expired: 'សម័យប្រើផុតកំណត់ សូមចូលម្តងទៀត',
    // Print & Export
    print_page: 'បោះពុម្ព',
    export_csv: 'CSV',
    export_json: 'JSON',
    print_receipt: 'វិក្កយបត្រ',
    receipt_title: 'វិក្កយបត្រ',
    receipt_no: 'លេខ',
    receipt_thank: 'អរគុណសម្រាប់ការទិញ!',
    // Notifications
    notifications: 'ការជូនដំណឹង',
    notif_low_stock: 'ស្តុកជិតអស់',
    notif_out_stock: 'អស់ស្តុក',
    no_notifications: 'មិនមានការជូនដំណឹង',
    mark_all_read: 'សម្គាល់ថាអានហើយ',
    // Stock adjust
    adjust_stock: 'កែតម្រូវស្តុក',
    add_stock: 'បន្ថែម',
    reason: 'មូលហេតុ',
    // Misc
    profit_per_item: 'ចំណេញ/ឯកតា',
    confirm_yes: 'យល់ព្រម',
    confirm_no: 'បោះបង់',
    loading: 'កំពុងផ្ទុក...',
    all_time_sales: 'ការលក់សរុប',
    all_time_purchases: 'ការទិញសរុប',
    net_profit: 'ចំណេញសុទ្ធ',
    quick_add: 'បន្ថែមរហ័ស',
    shortcut_hint: 'Ctrl+N: បន្ថែម  |  Ctrl+P: បោះពុម្ព',
    page_report: 'របាយការណ៍',
    generated_on: 'បង្កើតនៅ',
    print_by: 'បោះពុម្ពដោយ',
  },
  en: {
    app_name: 'Littlemaker', app_tagline: 'Business Management System',
    nav_dashboard: 'Dashboard', nav_products: 'Products',
    nav_sales: 'Sales', nav_purchases: 'Purchases', nav_settings: 'Settings',
    add: 'Add', edit: 'Edit', delete: 'Delete', save: 'Save',
    cancel: 'Cancel', search: 'Search...', confirm_delete: 'Are you sure you want to delete?',
    total_products: 'Total Products', total_sales: 'Total Sales',
    total_purchases: 'Total Purchases', profit: 'Net Profit',
    recent_sales: 'Recent Sales', recent_purchases: 'Recent Purchases',
    product_name: 'Product Name', category: 'Category',
    buy_price: 'Buy Price (KHR)', sell_price: 'Sell Price (KHR)',
    stock: 'Stock', unit: 'Unit', manage_products: 'Manage Products',
    add_product: 'Add Product', edit_product: 'Edit Product',
    manage_sales: 'Manage Sales', add_sale: 'Record Sale',
    customer: 'Customer', quantity: 'Quantity', total: 'Total',
    date: 'Date', product: 'Product', unit_price: 'Unit Price',
    note: 'Note', sale_history: 'Sales History',
    manage_purchases: 'Manage Purchases', add_purchase: 'Record Purchase',
    supplier: 'Supplier', purchase_history: 'Purchase History',
    saved: '✓ Saved successfully!', deleted: '✓ Deleted successfully!',
    insufficient_stock: '⚠ Insufficient stock!', fill_required: '⚠ Please fill required fields!',
    low_stock: 'Low Stock', in_stock: 'In Stock', out_stock: 'Out of Stock',
    unit_pcs: 'pcs', unit_kg: 'kg', unit_liter: 'ltr', unit_box: 'box', unit_pack: 'pack', unit_can: 'can', unit_bottle: 'bottle',
    cat_food: 'Food', cat_drink: 'Drink', cat_material: 'Material', cat_other: 'Other',
    all_categories: 'All Categories', no_data: 'No data available', items: 'items',
    filter_date: 'Filter by Date', today: 'Today', this_week: 'This Week',
    this_month: 'This Month', all_time: 'All Time', actions: 'Actions',
    profit_margin: 'Profit Margin', top_products: 'Top Selling Products',
    dashboard_summary: 'Overview Summary',
    // Settings
    settings_title: 'System Settings',
    settings_appearance: '🎨 Appearance',
    settings_language: 'Language',
    settings_theme: 'Display Mode',
    settings_theme_light: '☀️ Light',
    settings_theme_dark: '🌙 Dark',
    settings_theme_auto: '🔄 Auto',
    settings_business: '🏪 Business Info',
    settings_biz_name: 'Shop Name',
    settings_biz_phone: 'Phone Number',
    settings_biz_address: 'Address',
    settings_receipt_footer: 'Receipt Footer Text',
    settings_data: '💾 Data Management',
    settings_export_json: 'Export JSON (All Data)',
    settings_import_json: 'Import JSON',
    settings_reset: '🗑 Delete All Data',
    settings_reset_confirm: 'Delete ALL data? This action cannot be undone!',
    settings_saved: '✓ Settings saved!',
    settings_reset_done: '✓ Data has been cleared!',
    settings_import_success: '✓ Data imported successfully!',
    settings_import_error: '⚠ Invalid file format!',
    settings_about: 'ℹ️ About',
    settings_version: 'Version',
    settings_save_btn: 'Save Settings',
    // Login
    login_title: 'Sign In', login_subtitle: 'Business Management System',
    username: 'Username', password: 'Password',
    login_btn: 'Sign In', logout_btn: 'Sign Out',
    login_error: '⚠ Incorrect username or password!',
    login_required: '⚠ Please fill in all fields!',
    remember_me: 'Remember me',
    settings_users: '👥 User Management',
    user_add: 'Add User', user_edit: 'Edit User',
    user_name_label: 'Username', user_display: 'Display Name',
    user_role: 'Role', role_admin: 'Admin', role_staff: 'Staff',
    user_new_pass: 'New Password (leave blank to keep current)',
    logged_in_as: 'Signed in as',
    session_expired: 'Session expired, please sign in again',
    // Print & Export
    print_page: 'Print',
    export_csv: 'CSV',
    export_json: 'JSON',
    print_receipt: 'Receipt',
    receipt_title: 'Invoice',
    receipt_no: 'No.',
    receipt_thank: 'Thank you for your purchase!',
    // Notifications
    notifications: 'Notifications',
    notif_low_stock: 'Low Stock',
    notif_out_stock: 'Out of Stock',
    no_notifications: 'No notifications',
    mark_all_read: 'Mark all as read',
    // Stock adjust
    adjust_stock: 'Adjust Stock',
    add_stock: 'Add',
    reason: 'Reason',
    // Misc
    profit_per_item: 'Profit/unit',
    confirm_yes: 'Confirm',
    confirm_no: 'Cancel',
    loading: 'Loading...',
    all_time_sales: 'Total Sales',
    all_time_purchases: 'Total Purchases',
    net_profit: 'Net Profit',
    quick_add: 'Quick Add',
    shortcut_hint: 'Ctrl+N: Add  |  Ctrl+P: Print',
    page_report: 'Report',
    generated_on: 'Generated on',
    print_by: 'Printed by',
  }
};

let currentLang = localStorage.getItem('lm_lang') || 'km';
function t(key) { return translations[currentLang][key] || key; }
function switchLang(lang) { currentLang = lang; localStorage.setItem('lm_lang', lang); location.reload(); }
function applyLang() {
  document.querySelectorAll('[data-t]').forEach(el => el.textContent = t(el.dataset.t));
  document.querySelectorAll('[data-tp]').forEach(el => el.placeholder = t(el.dataset.tp));
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active', b.dataset.lang === currentLang));
  document.body.dataset.lang = currentLang;
  // Update html lang attr
  document.documentElement.lang = currentLang === 'km' ? 'km' : 'en';
}

// Injected additions - Recycle Bin & History
(function() {
  const addKm = {
    recycle_bin: '🗑 Recycle Bin',
    nav_history: '📋 ប្រវត្តិ',
    move_to_bin: 'ផ្ញើទៅ Recycle Bin',
    restore: 'Restore / ស្ដារ',
    perm_delete: 'លុបអចិន្ត្រៃ',
    confirm_move_bin: 'ផ្ញើផលិតផលទៅ Recycle Bin?',
    confirm_perm_delete: 'លុបអចិន្ត្រៃ? មិនអាចត្រឡប់វិញ!',
    confirm_empty_bin: 'លុបផលិតផលទាំងអស់ក្នុង Recycle Bin?',
    confirm_clear_history: 'លុប History ទាំងអស់?',
    moved_to_bin: '✓ បានផ្ញើទៅ Recycle Bin',
    restored: 'ត្រូវបាន Restore ជោគជ័យ',
    perm_deleted: '✓ លុបអចិន្ត្រៃជោគជ័យ',
    bin_emptied: '✓ Recycle Bin ទទេហើយ',
    bin_empty: '🗑 Recycle Bin ទទេ — មិនមានផលិតផលណានៅទីនេះ',
    bin_desc: 'ផលិតផលដែលបានលុបនឹងស្ថិតនៅទីនេះ អ្នកអាច Restore ពេលណាក៏បាន',
    empty_bin: 'លុបចោលទាំងអស់',
    history_desc: 'ប្រវត្តិការផ្លាស់ប្ដូរផលិតផលទាំងអស់',
    clear_history: 'លុប History',
    history_cleared: '✓ History ត្រូវបានលុប',
    no_history: '📋 មិនមាន History នៅឡើយ',
    history_detail: 'ព័ត៌មានលម្អិត',
    view_detail: 'មើលព័ត៌មាន',
    hist_add: 'បន្ថែម',
    hist_edit: 'កែប្រែ',
    hist_delete: 'លុប',
    hist_restore: 'Restore',
    hist_perm_delete: 'លុបអចិន្ត្រៃ',
    hist_adjust: 'កែស្តុក',
    close: 'បិទ',
  };
  const addEn = {
    recycle_bin: '🗑 Recycle Bin',
    nav_history: '📋 History',
    move_to_bin: 'Move to Recycle Bin',
    restore: 'Restore',
    perm_delete: 'Delete permanently',
    confirm_move_bin: 'Move product to Recycle Bin?',
    confirm_perm_delete: 'Permanently delete? This cannot be undone!',
    confirm_empty_bin: 'Empty the entire Recycle Bin?',
    confirm_clear_history: 'Clear all History?',
    moved_to_bin: '✓ Moved to Recycle Bin',
    restored: 'restored successfully',
    perm_deleted: '✓ Permanently deleted',
    bin_emptied: '✓ Recycle Bin emptied',
    bin_empty: '🗑 Recycle Bin is empty',
    bin_desc: 'Deleted products are stored here. You can restore them anytime.',
    empty_bin: 'Empty Bin',
    history_desc: 'Full history of all product changes',
    clear_history: 'Clear History',
    history_cleared: '✓ History cleared',
    no_history: '📋 No history yet',
    history_detail: 'Detail',
    view_detail: 'View detail',
    hist_add: 'Added',
    hist_edit: 'Edited',
    hist_delete: 'Deleted',
    hist_restore: 'Restored',
    hist_perm_delete: 'Perm. deleted',
    hist_adjust: 'Stock adj.',
    close: 'Close',
  };
  Object.assign(translations.km, addKm);
  Object.assign(translations.en, addEn);
})();
